title: Georgia Clay, PhD
logo: "/images/headshot.jpg?raw=true" 
description: 
  <br>
  Data Analyst with commercial experience in data science/analytics and doctorate degree in Natural Sciences from the University of Vienna.
  <br><br>
  <a href="https://www.linkedin.com/in/georgia-clay-phd-28ba96166/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
